__MAJOR__ = 0
__MINOR__ = 1
__MICRO__ = 4
__RELEASE__ = ''  # a #b  # https://www.python.org/dev/peps/pep-0440/#public-version-identifiers --> alpha beta, ...
__VERSION__ = f'{__MAJOR__}.{__MINOR__}.{__MICRO__}{__RELEASE__}'
__DESCRIPTION__ = """PyFigures will assist you assemble publication ready scientific figures in no time."""
__URL__ = 'https://github.com/baigouy/PyFigures'
__SHORT__NAME__ = 'PyFigures'
__NAME__ = f'{__SHORT__NAME__}: Effortless Creation of High-Quality Scientific Figures'  # TODO think about a name and how to handle that # PyFigures --> other possible name
__EMAIL__ = 'benoit.aigouy@gmail.com'
__AUTHOR__ = 'Benoit Aigouy'
